version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ai_postgres
    restart: always
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: aibackend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
